(defun mensaje-1() (format t "~%Es tu turno: "))
(defun mensaje-2() (format t "~%********************************"))
(defun mensaje-3() (format t "~%"))
(defun mensaje-4() (format t "~%Escoge: "))
(defun mensaje-5() (format t "~%Selecciona tu ficha: "))

(defun opciones-movimientos ()
	(format t "~&Opciones de movimientos")
	(dotimes (contador 8 ) 
	  (format t "~&~s [ ~s ]"
			(case (+ contador 1)
				(1 'Desplazar-Izquierda)
				(2 'Desplazar-Derecha)
				(3 'Desplazar-Arriba)
				(4 'Desplazar-Abajo)
				(5 'Desplazar-Diagonal-a-derecha)
				(6 'Desplazar-Diagonal-a-izquierda)
				(7 'Desplazar-Diagonal-b-derecha)
				(8 'Desplazar-Diagonal-b-izquierda) )
			(+ contador 1) ) ) )

(defun cuerpo()
	(let (
		(Indice NIL)
		(Movimiento NIL) )
		(progn
			(if (es-primera-fase-p)
				(progn
					(mensaje-1)
					(mensaje-2)
					(setq Indice (read))
					(poner (coordenada Indice) *Humano*)
					(obtener-primero-mejor)
					(jugar) )
				(progn
					(mensaje-5)
					(mensaje-3)
					(loop
						(setq Indice (read))
						(when (and (>= Indice 1) (<= Indice 8)) (return))
						(format t "~%Vuelve a intentarlo :P~%")
						(mostrar-tablero)
						(mensaje-3) )
					(opciones-movimientos)
					(mensaje-4)
					(mensaje-3)
					(loop
						(print 'En-el-loop)
						(setq Movimiento (read))
						(when (and (>= Movimiento 1) (<= Movimiento 8)) (return))
						(format t "~%Vuelve a intentarlo :P~%")
						(mostrar-tablero)
						(mensaje-3) )
					(cond
						( (eq Movimiento 1) (desplazar-izquierda (coordenada Indice) *Humano*) )
						( (eq Movimiento 2) (desplazar-derecha (coordenada Indice) *Humano*) )
						( (eq Movimiento 3) (desplazar-arriba (coordenada Indice) *Humano*) )
						( (eq Movimiento 4) (desplazar-abajo (coordenada Indice) *Humano*) )
						( (eq Movimiento 5) (desplazar-diagonal-a-derecha (coordenada Indice) *Humano*) )
						( (eq Movimiento 6) (desplazar-diagonal-a-izquierda (coordenada Indice) *Humano*) )
						( (eq Movimiento 7) (desplazar-diagonal-b-derecha (coordenada Indice) *Humano*) )
						( (eq Movimiento 8) (desplazar-diagonal-b-izquierda (coordenada Indice) *Humano*) ) )
					(obtener-primero-mejor)
					(jugar) ) ) ) ) )
(defun jugar()
	; Verficar si existe ganado e imprimir mensaje
	(mensaje-3)
	(mensaje-2)
	(format t "~&***JUEGO DE MORRIS - 3 FICHAS***")
	(mensaje-2)
	(mostrar-tablero)
	(cuerpo)
)

